DEFAULT_TARGET_LANG = "zh-CN"

# GB/T 7713.1 convention: headings use a heiti (sans) CJK face while body text
# stays in a songti (serif) face with Times New Roman for Latin glyphs.
GBT_HEADING_FONT_STACK = [
    "Times New Roman",
    "SimHei",
    "Heiti SC",
    "Noto Sans CJK SC",
    "Source Han Sans SC",
    "sans-serif",
]

DEFAULT_RENDER_DEFAULTS = {
    "target_lang": DEFAULT_TARGET_LANG,
    "font_stack": [
        "Times New Roman",
        "SimSun",
        "Songti SC",
        "Noto Serif CJK SC",
        "Source Han Serif SC",
        "serif",
    ],
    "line_height": 1.35,
    "paragraph_spacing_em": 0.45,
    "layout_mode": "continuous_reflow",
    "formula_numbering": "none",
    "page_layout": {
        "width_pt": 595.28,
        "height_pt": 841.89,
        "margin_top_pt": 70.87,
        "margin_right_pt": 56.69,
        "margin_bottom_pt": 56.69,
        "margin_left_pt": 70.87,
    },
    "role_styles": {
        "title": {
            "font_size_pt": 18.0,
            "bold": True,
            "italic": False,
            "alignment": "center",
            "line_height": 1.5,
            "first_line_indent_em": 0.0,
            "space_before_pt": 0.0,
            "space_after_pt": 18.0,
            "font_stack": GBT_HEADING_FONT_STACK,
        },
        "abstract": {
            "font_size_pt": 12.0,
            "bold": False,
            "italic": False,
            "alignment": "justify",
            "line_height": 1.5,
            "first_line_indent_em": 2.0,
            "space_before_pt": 6.0,
            "space_after_pt": 6.0,
        },
        "heading": {
            "font_size_pt": 14.0,
            "bold": True,
            "italic": False,
            "alignment": "left",
            "line_height": 1.5,
            "first_line_indent_em": 0.0,
            "space_before_pt": 12.0,
            "space_after_pt": 6.0,
            "font_stack": GBT_HEADING_FONT_STACK,
        },
        "paragraph": {
            "font_size_pt": 12.0,
            "bold": False,
            "italic": False,
            "alignment": "justify",
            "line_height": 1.5,
            "first_line_indent_em": 2.0,
            "space_before_pt": 0.0,
            "space_after_pt": 6.0,
        },
        "caption": {
            "font_size_pt": 10.5,
            "bold": False,
            "italic": False,
            "alignment": "center",
            "line_height": 1.35,
            "first_line_indent_em": 0.0,
            "space_before_pt": 4.0,
            "space_after_pt": 6.0,
        },
        "formula": {
            "font_size_pt": 12.0,
            "bold": False,
            "italic": False,
            "alignment": "center",
            "line_height": 1.35,
            "first_line_indent_em": 0.0,
            "space_before_pt": 6.0,
            "space_after_pt": 6.0,
        },
        "table": {
            "font_size_pt": 10.5,
            "bold": False,
            "italic": False,
            "alignment": "center",
            "line_height": 1.25,
            "first_line_indent_em": 0.0,
            "space_before_pt": 4.0,
            "space_after_pt": 6.0,
        },
        "figure": {
            "font_size_pt": 10.5,
            "bold": False,
            "italic": False,
            "alignment": "center",
            "line_height": 1.35,
            "first_line_indent_em": 0.0,
            "space_before_pt": 4.0,
            "space_after_pt": 6.0,
        },
        "footnote": {
            "font_size_pt": 10.5,
            "bold": False,
            "italic": False,
            "alignment": "justify",
            "line_height": 1.25,
            "first_line_indent_em": 0.0,
            "space_before_pt": 0.0,
            "space_after_pt": 4.0,
        },
        "reference": {
            "font_size_pt": 10.5,
            "bold": False,
            "italic": False,
            "alignment": "left",
            "line_height": 1.25,
            "first_line_indent_em": 0.0,
            "space_before_pt": 0.0,
            "space_after_pt": 4.0,
        },
        "unknown": {
            "font_size_pt": 12.0,
            "bold": False,
            "italic": False,
            "alignment": "left",
            "line_height": 1.5,
            "first_line_indent_em": 0.0,
            "space_before_pt": 0.0,
            "space_after_pt": 6.0,
        },
    },
    "alignment": {
        "title": "center",
        "abstract": "justify",
        "heading": "left",
        "paragraph": "justify",
        "caption": "center",
        "formula": "center",
        "table": "center",
        "figure": "center",
        "footnote": "justify",
        "reference": "left",
        "unknown": "left",
    },
    "overflow_policy": {
        "strategy": "scale_then_expand_then_continue",
        "min_font_scale": 0.86,
        "max_font_scale": 1.0,
        "allow_box_expansion": True,
        "allow_continuation_page": True,
    },
    "preserve_policy": {
        "formulas": "preserve",
        "citations": "preserve",
        "reference_markers": "preserve",
        "figure_table_assets": "preserve",
        "whitespace": "allow_reflow",
        "line_breaks": "allow_reflow",
    },
}
